name: "roi_param_optimizer_preprocessing"

use_color_constancy: true
color_constancy_method: "gray_world" # "gray_world" ebner

use_resize: false
resize_size: [64, 64]

debug_visualize: true
debug_visualize_dir: "${base_dir}/results/roi_param_optimizer_preprocessing_visualize"

color_space: "bgr"