name: "multi_color_detector"

params_dir: "${base_dir}/models/roi_detection/"



min_area: 3000
max_area: 30000
min_aspect_ratio: 0.8
max_aspect_ratio: 1.2

threshold_error_dict:
  "1": 5
  "2": 5
  "3": 5
  "4": 10
  "5": 5
  "6": 5
  "7": 10
  "8": 5
  "9": 5
  "10": 5
  "11": 30
  "12": 0
  "13": 5
  "14": 10
