name: "multi_color_detector"

params_dir: "${base_dir}/models/roi_detection/"



min_area: 3000
max_area: 30000
min_aspect_ratio: 0.8
max_aspect_ratio: 1.2
fill_ratio: 0.78
threshold_error_dict:
  "1": 2
  "2": 2
  "3": 5
  "4": 5
  "5": 15
  "6": 5
  "7": 10
  "8": 5
  "9": 5
  "10": 5
  "11": 10
  "12": 5
  "13": 5

